import { getServerQueryClient,queryKeys } from "@/db/query/tanstack-query";
import { Hydrate,dehydrate } from "@tanstack/react-query";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";
import { getUsers } from "./actions";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: PropsWithChildren) {
  const queryKey = queryKeys.users.list().queryKey;

  const queryClient = getServerQueryClient();
  await queryClient.prefetchQuery(queryKey, () => getUsers());
  const dehydratedState = dehydrate(queryClient);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Hydrate state={dehydratedState}>{children}</Hydrate>
        </Providers>
      </body>
    </html>
  );
}
